### ISSUE TITLE
a question abouts the ’generic.gin ‘

### ISSUE THREAD

**Issue by Pein-hub** [ElementAI/N-BEATS#5]
In experiments/m4/generic.gin, 
`
instance.history_size = {
    'Yearly': 1.5,
    'Quarterly': 1.5,
    'Monthly': 1.5,
    'Weekly': 10,
    'Daily': 10,
    'Hourly': 10
}

instance.iterations = {
    'Yearly': 15000,
    'Quarterly': 15000,
    'Monthly': 15000,
    'Weekly': 5000,
    'Daily': 5000,
    'Hourly': 5000
}
`
How are the above parameters determined？

**Comment by PhilippeChatigny** [comment]
![image](https://user-images.githubusercontent.com/13261367/93633658-4f223b00-f9bd-11ea-9fdf-573b2172431e.png)
fyi: @Pein-hub these parameters are the one used in the original paper to produce their forecast.

**Comment by Pein-hub** [comment]
thank u!
